# from: https://medium.com/slalom-build/pre-commit-hooks-for-terraform-9356ee6db882

repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.18 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.236'
  hooks:
    - id: ruff
